### ISSUE TITLE
Fatal Error, Please help

### ISSUE THREAD

**Issue by ngangchill** [raulr/google-play-scraper#1]
Fatal error: Uncaught exception 'GuzzleHttp\Exception\RequestException' with message 'cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)' in C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\projects\google-play-scraper-master\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:187 Stack trace: #0 C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\projects\google-play-scraper-master\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(150): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array) #1 C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\projects\google-play-scraper-master\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(103): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory)) #2 C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\loc in C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\projects\google-play-scraper-master\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php on line 187

**Comment by raulr** [comment]
Looks like your system (Windows) doesn't have the root CA certificates needed by Curl. Try [this solution](http://stackoverflow.com/a/21114601).

**Comment by undefinedor** [comment]
Why not use Linux such as Ubuntu?
