### ISSUE TITLE
The current node list is empty.

### ISSUE THREAD

**Issue by Ashutosh1507** [raulr/google-play-scraper#15]
Hi, 
I have been using this scrapper for a long time.
But since yesterday we are not able to scrap any values from the playstore. 
We are getting error "The current node list is empty".

Can you please help us out with this issue.

**Comment by mehmetsoylucom** [comment]
I'm living same problem.

**Comment by gauravgoyal1211** [comment]
I am also getting same issue.
Please resolve it ASAP. It's urgent..... 
Thanks

**Comment by mehmetsoylucom** [comment]
I used Goutte Client for scrapping for now.

``  $crawler = $playStoreScraper->request('GET', 'https://play.google.com/store/apps/details?id=hu.viala.newiapp&hl=en');

$result['title'] = $crawler->filter('[itemprop=name]')->text();
$result['image'] = $crawler->filter("[itemprop=image]")->attr('src');
``

**Comment by alexspyr** [comment]
I have exactly the same problem!!!
Did Google block this lib or changed they way they structure their data?

**Comment by am3do** [comment]
Hi, I have the same issue. I'd really appreciate a solution. Thanks a lot!

**Comment by raulr** [comment]
The google play site structure has changed and it seems they have obfuscated css class names.

Can you check if branch [hotfix-15](/raulr/google-play-scraper/tree/hotfix-15) works for you? At least for app detail scrapping.

**Comment by Ashutosh1507** [comment]
It work for me. but as @am3do mentioned i have to comment out the line $info['url'] = $crawler->filter('link[rel="canonical"]')->eq(1)->attr('href');
It worked after commenting the line.
Thanks for the fix :)

**Comment by mayurKul** [comment]
Hi,
I am getting the same error.
The current node list is empty.

**Comment by michaelcmundo** [comment]
Hi Is there another hot fix? I tried the hotfix branch and comment out that line but still not work with that error message.

**Comment by Ashutosh1507** [comment]
The same issue current node list is empty is occurring today again.
Is there any more fix required?

**Comment by lescha1983** [comment]
Same problem

**Comment by Ashutosh1507** [comment]
Hi.. When the issue is going to be fixed? Can we have some workaround for this?
@am3do is the latest fix working for you. Any suggestions are welcome.We are  stuck due to this issue

**Comment by am3do** [comment]
Hi! Unfortunately there are different issues from time to time, so I am not using that code anymore. It’s a pity since the base is really great. It is google who causes the difficulties because of frequent changes in the site structure. So it is more than reasonable that Raul seems to be sick of fixing that again and again.

**Comment by raulr** [comment]
Hi,

The google play site markup changed again, making it even harder to parse. I've added a new commit to `hotfix-15` branch that should work for app scraping.

Unfortunatelly list retrieving is totally broken. I don't have much time to spend in this, so any pull request is welcome.

@am3do, the code mainly uses Symfony's DomCrawler component, I think most of the code could be understood after reading its documentation:
https://symfony.com/doc/current/components/dom_crawler.html
https://api.symfony.com/master/Symfony/Component/DomCrawler/Crawler.html

**Comment by droidmanspace** [comment]
I moved to node.js ,made a server for google play scrapper which can be consumed by php project over API call.

**Comment by am3do** [comment]
Hi, @raulr! Thanks you!

**Comment by martarodriguezm** [comment]
Hi,
The hotfix-15 works perfect for me, thank you very much @raulr !!
