### ISSUE TITLE
"Class 'Scraper' not found"

### ISSUE THREAD

**Issue by hAtul89** [raulr/google-play-scraper#4]
Using UBUNTU SERVER: 
I installed it to my CodeIgniter using composer: 
The folder of `raulr` with all the rest of the directories were installed. 

I added to the top of my controller this part as usual: 
`require FCPATH. 'vendor/autoload.php';`
In the same controller, it loads the PHPExcel library that works BTW.. 

But when running this: 

```
	public function test(){
		$scraper = new Scraper();
		var_dump($scraoer);
		$apps = $scraper->getList('topselling_free', 'poker');
		var_dump($apps);
	}
```

I get this error: 

> An uncaught Exception was encountered
> Type: Error
> Message: Class 'Scraper' not found
> Filename: /var/www/html/tools/application/controllers/stuff/Automation.php
> Line Number: 303

Why isn't the library getting loaded properly?

**Comment by raulr** [comment]
You must import the namespace at the top of the file.

```php
use Raulr\GooglePlayScraper\Scraper;
```
